export const clerkDarkAppearance = {
  variables: {
    colorBackground: "#0a0a0a",
    colorText: "#ffffff",
    colorTextSecondary: "#ffffff",
    colorTextOnPrimaryBackground: "#ffffff",
    colorInputBackground: "#000000",
    colorInputText: "#ffffff",
    colorNeutral: "#ffffff",
    colorPrimary: "#6db0fc",
    colorShimmer: "#1a1a1a",
    borderRadius: "0.75rem",
  },
  elements: {
    card: {
      backgroundColor: "#0a0a0a",
      border: "1px solid rgba(255,255,255,0.1)",
      boxShadow: "0 25px 50px rgba(0,0,0,0.8)",
    },
    headerTitle: { color: "#ffffff" },
    headerSubtitle: { color: "#ffffff" },
    socialButtonsBlockButton: {
      backgroundColor: "#000000",
      border: "1px solid rgba(255,255,255,0.3)",
      color: "#ffffff",
    },
    socialButtonsBlockButtonText: { color: "#ffffff" },
    socialButtonsBlockButtonArrow: { color: "#ffffff" },
    dividerLine: { backgroundColor: "rgba(255,255,255,0.2)" },
    dividerText: { color: "#ffffff" },
    formFieldLabel: { color: "#ffffff" },
    formFieldHintText: { color: "rgba(255,255,255,0.7)" },
    formFieldInput: {
      backgroundColor: "#000000",
      color: "#ffffff",
      border: "1px solid rgba(255,255,255,0.8)",
    },
    formFieldInputShowPasswordButton: { color: "#ffffff" },
    footerActionText: { color: "#ffffff" },
    footerActionLink: { color: "#6db0fc" },
    identityPreviewText: { color: "#ffffff" },
    identityPreviewEditButton: { color: "#6db0fc" },
    formResendCodeLink: { color: "#6db0fc" },
    alternativeMethodsBlockButton: {
      color: "#ffffff",
      border: "1px solid rgba(255,255,255,0.3)",
    },
    otpCodeFieldInput: {
      backgroundColor: "#000000",
      color: "#ffffff",
      border: "1px solid rgba(255,255,255,0.8)",
    },
  },
};
